"""
Chanakya v3 — EULA & Legal Text
"""

EULA_TEXT = """
CHANAKYA AI PLATFORM — USER AGREEMENT & DISCLAIMER
Version 1.0 | Effective Date: April 2026
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. ABOUT THIS PLATFORM
   Chanakya AI is an educational technology platform that 
   applies artificial intelligence to analyze stock and 
   commodity market patterns. It is built to help users 
   learn how AI interprets market data — not to tell you 
   what to buy or sell.

2. AI DECISION SUPPORT — NOT ADVICE
   The signals, scores, and analysis generated by Chanakya AI 
   are based on historical data patterns. AI models can 
   identify trends but cannot predict the future with certainty.
   Markets are influenced by news, geopolitical events, and 
   human emotions — factors that no algorithm can fully model.

   ✦ Treat AI signals as one input among many — not as 
     the final word on any trade.

3. YOUR DECISION, YOUR RESPONSIBILITY
   Every trade you place is your own decision. Chanakya AI 
   provides analysis — you control the action. You are solely 
   responsible for any profits or losses arising from trades 
   placed using insights from this platform.

4. REGULATORY DISCLOSURE
   Chanakya AI is not registered with the Securities and 
   Exchange Board of India (SEBI) as an Investment Advisor, 
   Research Analyst, or Broker. This platform does not 
   constitute investment advice under SEBI regulations.

   We strongly recommend consulting a SEBI-registered 
   financial advisor before making real-money investment 
   decisions.

5. MARKET RISK ACKNOWLEDGMENT
   The stock and commodity markets involve inherent risks. 
   The value of investments can go up or down based on 
   market conditions. Past pattern accuracy of our AI does 
   not imply similar results in the future.

6. SUBSCRIPTION & REFUND POLICY
   Subscription fees grant access to platform features only. 
   They are not payments for trading profits or guaranteed 
   returns. Once a subscription period begins, fees are 
   non-refundable. Subscriptions auto-expire at period end 
   and must be renewed to continue access.

7. DATA SECURITY
   Your broker API credentials are stored in encrypted form 
   and used solely to display your account data within the 
   platform. We do not share, sell, or transmit your data 
   to any third party.

8. PLATFORM AVAILABILITY
   We strive for high availability but do not guarantee 
   uninterrupted service. Market hours, API dependencies, 
   and maintenance windows may affect platform access.

9. ACCEPTANCE
   By registering and using Chanakya AI, you confirm that:
   ✦ You have read and understood this agreement
   ✦ You are 18 years of age or older
   ✦ You understand the risks of market trading
   ✦ You will use this platform for educational purposes
   ✦ You accept full responsibility for your trading decisions

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
For support: Contact admin via Telegram @chanakya_ai_dcp_bot
"""

SUBSCRIPTION_PLANS = {
    "monthly": {
        "label":    "1 Month",
        "days":     30,
        "price":    3000,
        "save":     0,
        "popular":  False,
        "badge":    "",
    },
    "quarterly": {
        "label":    "3 Months",
        "days":     90,
        "price":    8000,
        "save":     1000,
        "popular":  True,
        "badge":    "🔥 Popular",
    },
    "half_year": {
        "label":    "4 Months",
        "days":     120,
        "price":    9000,
        "save":     3000,
        "popular":  False,
        "badge":    "💰 Save ₹3,000",
    },
    "biannual": {
        "label":    "6 Months",
        "days":     180,
        "price":    13000,
        "save":     5000,
        "popular":  False,
        "badge":    "⭐ Best Value",
    },
    "annual": {
        "label":    "12 Months",
        "days":     365,
        "price":    25000,
        "save":     11000,
        "popular":  False,
        "badge":    "👑 Premium",
    },
}

def get_plan(plan_key):
    return SUBSCRIPTION_PLANS.get(plan_key)

def get_all_plans():
    plans = []
    for key, plan in SUBSCRIPTION_PLANS.items():
        plans.append({
            "key":     key,
            "label":   plan["label"],
            "days":    plan["days"],
            "price":   plan["price"],
            "save":    plan["save"],
            "popular": plan["popular"],
            "badge":   plan["badge"],
            "per_month": round(plan["price"] / (plan["days"]/30), 0),
        })
    return plans
